# Generated by Django 4.2 on 2023-05-28 06:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_brand'),
    ]

    operations = [
    ]
