# Generated by Django 4.2 on 2023-05-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_tables_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
