# Generated by Django 4.2 on 2023-05-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_created_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Example Brand', max_length=30),
            preserve_default=False,
        ),
    ]
