# Generated by Django 4.2 on 2023-05-12 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_userprofile_city'),
        ('products', '0003_product_brand'),
    ]

    operations = [
    ]
